CREATE_TABLE_GLYCAN = '''
CREATE TABLE GLYCAN (
    ID                  INT  PRIMARY KEY
                             NOT NULL,
    GLYCAN_NAME         TEXT,
    GLYCAN_STRUCT       TEXT NOT NULL,
    GLYCAN_COMPOSITION  TEXT NOT NULL,
    DECOY               INT  NOT NULL
);
'''

CREATE_TABLE_GLYCOSITE = '''
CREATE TABLE GLYCOSITE (
    ID                  INT  PRIMARY KEY
                             NOT NULL,
    GLYCOSITE_NAME      TEXT,
    PROTEIN_GLYCOSITE   TEXT NOT NULL,
    DECOY               INT  NOT NULL
);
'''

CREATE_TABLE_GLYCOSITE_PROTEIN_MAPPING = '''
CREATE TABLE GLYCOSITE_PROTEIN_MAPPING (
    GLYCOSITE_ID        INT NOT NULL,
    PROTEIN_ID          INT NOT NULL
);
'''

CREATE_TABLE_GLYCOPEPTIDE = '''
CREATE TABLE GLYCOPEPTIDE (
    ID                  INT  PRIMARY KEY
                             NOT NULL,
    GLYCOPEPTIDE_NAME   TEXT,
    GLYCAN_SITE         INT,
    DECOY_PEPTIDE       INT  NOT NULL,
    DECOY_GLYCAN        INT  NOT NULL
);
'''

CREATE_TABLE_GLYCOPEPTIDE_GLYCOSITE_MAPPING = '''
CREATE TABLE GLYCOPEPTIDE_GLYCOSITE_MAPPING (        
    GLYCOPEPTIDE_ID     INT NOT NULL,
    GLYCOSITE_ID       INT NOT NULL
);
'''

CREATE_TABLE_GLYCOPEPTIDE_GLYCAN_MAPPING = '''
CREATE TABLE GLYCOPEPTIDE_GLYCAN_MAPPING (
    GLYCOPEPTIDE_ID       INT NOT NULL,
    GLYCAN_ID           INT NOT NULL
);
'''

CREATE_TABLE_GLYCOPEPTIDE_PEPTIDE_MAPPING = '''
CREATE TABLE GLYCOPEPTIDE_PEPTIDE_MAPPING (        
    GLYCOPEPTIDE_ID     INT NOT NULL,
    PEPTIDE_ID       INT NOT NULL
);
'''

CREATE_TABLE_PRECURSOR_GLYCOPEPTIDE_MAPPING = '''
CREATE TABLE PRECURSOR_GLYCOPEPTIDE_MAPPING (
    PRECURSOR_ID        INT NOT NULL,
    GLYCOPEPTIDE_ID     INT NOT NULL
);
'''


SELECT_GLYCOPEPTIDE = '''
SELECT * FROM GLYCOPEPTIDE
'''

SELECT_GLYCOSITE = '''
SELECT * FROM GLYCOSITE
'''

SELECT_GLYCAN = '''
SELECT * FROM GLYCAN
'''


JOIN_PRECURSOR_GLYCOPEPTIDE = '''
INNER JOIN (
    SELECT PRECURSOR_ID AS ID, GLYCOPEPTIDE_ID 
    FROM PRECURSOR_GLYCOPEPTIDE_MAPPING
)
USING (ID)
'''

JOIN_GLYCOPEPTIDE_PEPTIDE = '''
INNER JOIN (
    SELECT GLYCOPEPTIDE_ID AS ID, PEPTIDE_ID 
    FROM GLYCOPEPTIDE_PEPTIDE_MAPPING
)
USING (ID)
'''

JOIN_GLYCOPEPTIDE_GLYCOSITE = '''
INNER JOIN (
    SELECT GLYCOPEPTIDE_ID AS ID, GLYCOSITE_ID 
    FROM GLYCOPEPTIDE_GLYCOSITE_MAPPING
)
USING (ID)
'''

JOIN_GLYCOPEPTIDE_GLYCAN = '''
INNER JOIN (
    SELECT GLYCOPEPTIDE_ID AS ID, GLYCAN_ID 
    FROM GLYCOPEPTIDE_GLYCAN_MAPPING
)
USING (ID)
'''

JOIN_GLYCOSITE_PROTEIN = '''
INNER JOIN (
    SELECT GLYCOSITE_ID AS ID, PROTEIN_ID 
    FROM GLYCOSITE_PROTEIN_MAPPING
)
USING (ID)
'''

SELECT_MAX_ID_GLYCOPEPTIDE = '''
SELECT MAX(ID) FROM GLYCOPEPTIDE
'''

SELECT_MAX_ID_GLYCOSITE = '''
SELECT MAX(ID) FROM GLYCOSITE
'''

SELECT_MAX_ID_GLYCAN = '''
SELECT MAX(ID) FROM GLYCAN
'''
