library(RSQLite)

read.detecting.transitions = function(path, 
                                      modified_sequence,
                                      glycan_site,
                                      glycan_name,
                                      precursor_charge) {
  conn = dbConnect(RSQLite::SQLite(), path)
  
  query = "
SELECT PRECURSOR_MZ,
       PRECURSOR.CHARGE AS PRECURSOR_CHARGE,
       LIBRARY_RT,
       PRODUCT_MZ,
       TRANSITION.CHARGE AS PRODUCT_CHARGE,
       TRANSITION.TYPE AS FRAGMENT_TYPE,
       ANNOTATION,
       TRANSITION.LIBRARY_INTENSITY AS PRODUCT_INTENSITY
FROM PRECURSOR
INNER JOIN TRANSITION_PRECURSOR_MAPPING ON TRANSITION_PRECURSOR_MAPPING.PRECURSOR_ID = PRECURSOR.ID
INNER JOIN TRANSITION ON TRANSITION.ID = TRANSITION_PRECURSOR_MAPPING.TRANSITION_ID

INNER JOIN PRECURSOR_GLYCOPEPTIDE_MAPPING ON PRECURSOR_GLYCOPEPTIDE_MAPPING.PRECURSOR_ID = PRECURSOR.ID
INNER JOIN GLYCOPEPTIDE ON GLYCOPEPTIDE.ID = PRECURSOR_GLYCOPEPTIDE_MAPPING.GLYCOPEPTIDE_ID
INNER JOIN GLYCOPEPTIDE_PEPTIDE_MAPPING ON GLYCOPEPTIDE_PEPTIDE_MAPPING.GLYCOPEPTIDE_ID = GLYCOPEPTIDE.ID
INNER JOIN PEPTIDE ON GLYCOPEPTIDE_PEPTIDE_MAPPING.PEPTIDE_ID = PEPTIDE.ID
INNER JOIN GLYCOPEPTIDE_GLYCAN_MAPPING ON GLYCOPEPTIDE_GLYCAN_MAPPING.GLYCOPEPTIDE_ID = GLYCOPEPTIDE.ID
INNER JOIN GLYCAN ON GLYCAN.ID = GLYCOPEPTIDE_GLYCAN_MAPPING.GLYCAN_ID

WHERE TRANSITION.DETECTING = 1
  AND PEPTIDE.MODIFIED_SEQUENCE = ?
  AND GLYCAN.GLYCAN_NAME = ?
  AND GLYCOPEPTIDE.GLYCAN_SITE = ?
  AND PRECURSOR.CHARGE = ?
"
  
  transitions = dbGetQuery(
    conn, query, 
    params = c(
      modified_sequence,
      glycan_name,
      glycan_site,
      precursor_charge
    )
  )
  colnames(transitions) = tolower(colnames(transitions))
  
  dbDisconnect(conn)
  transitions
}

read.identifying.transitions = function(path, 
                                        modified_sequence,
                                        glycan_site,
                                        glycan_name,
                                        precursor_charge) {
  conn = dbConnect(RSQLite::SQLite(), path)
  
  query = "
SELECT GLYCAN.GLYCAN_NAME AS GLYCAN,
       PRECURSOR_MZ,
       PRECURSOR.CHARGE AS PRECURSOR_CHARGE,
       LIBRARY_RT,
       PRODUCT_MZ,
       TRANSITION.CHARGE AS PRODUCT_CHARGE,
       TRANSITION.TYPE AS FRAGMENT_TYPE,
       ANNOTATION,
       TRANSITION.LIBRARY_INTENSITY AS PRODUCT_INTENSITY,
       GLYCOFORM.GLYCAN_NAME AS GLYCOFORM
FROM PRECURSOR
INNER JOIN TRANSITION_PRECURSOR_MAPPING ON TRANSITION_PRECURSOR_MAPPING.PRECURSOR_ID = PRECURSOR.ID
INNER JOIN TRANSITION ON TRANSITION.ID = TRANSITION_PRECURSOR_MAPPING.TRANSITION_ID

INNER JOIN PRECURSOR_GLYCOPEPTIDE_MAPPING ON PRECURSOR_GLYCOPEPTIDE_MAPPING.PRECURSOR_ID = PRECURSOR.ID
INNER JOIN GLYCOPEPTIDE ON GLYCOPEPTIDE.ID = PRECURSOR_GLYCOPEPTIDE_MAPPING.GLYCOPEPTIDE_ID
INNER JOIN GLYCOPEPTIDE_PEPTIDE_MAPPING ON GLYCOPEPTIDE_PEPTIDE_MAPPING.GLYCOPEPTIDE_ID = GLYCOPEPTIDE.ID
INNER JOIN PEPTIDE ON GLYCOPEPTIDE_PEPTIDE_MAPPING.PEPTIDE_ID = PEPTIDE.ID
INNER JOIN GLYCOPEPTIDE_GLYCAN_MAPPING ON GLYCOPEPTIDE_GLYCAN_MAPPING.GLYCOPEPTIDE_ID = GLYCOPEPTIDE.ID
INNER JOIN GLYCAN ON GLYCAN.ID = GLYCOPEPTIDE_GLYCAN_MAPPING.GLYCAN_ID

INNER JOIN (
  SELECT TRANSITION_ID, 
         GLYCAN.*
  FROM TRANSITION_GLYCOPEPTIDE_MAPPING 
  INNER JOIN GLYCOPEPTIDE AS GLYCOPEPTIDE ON GLYCOPEPTIDE.ID = TRANSITION_GLYCOPEPTIDE_MAPPING.GLYCOPEPTIDE_ID
  INNER JOIN GLYCOPEPTIDE_GLYCAN_MAPPING ON GLYCOPEPTIDE_GLYCAN_MAPPING.GLYCOPEPTIDE_ID = GLYCOPEPTIDE.ID
  INNER JOIN GLYCAN ON GLYCAN.ID = GLYCOPEPTIDE_GLYCAN_MAPPING.GLYCAN_ID
) AS GLYCOFORM ON GLYCOFORM.TRANSITION_ID = TRANSITION.ID
  
INNER JOIN (
  SELECT DISTINCT 
         FEATURE.PRECURSOR_ID AS PRECURSOR_ID,
         FEATURE_TRANSITION.TRANSITION_ID AS TRANSITION_ID
  FROM FEATURE
  INNER JOIN SCORE_MS2 ON SCORE_MS2.FEATURE_ID = FEATURE.ID
  INNER JOIN FEATURE_TRANSITION ON FEATURE_TRANSITION.FEATURE_ID = FEATURE.ID
  WHERE SCORE_MS2.RANK = 1
) AS FEATURE_TRANSITION ON FEATURE_TRANSITION.TRANSITION_ID = TRANSITION.ID
  
WHERE TRANSITION.IDENTIFYING = 1
  AND TRANSITION.DECOY = 0
  AND PEPTIDE.MODIFIED_SEQUENCE = ?
  AND GLYCAN.GLYCAN_NAME = ?
  AND GLYCOPEPTIDE.GLYCAN_SITE = ?
  AND PRECURSOR.CHARGE = ?
"
  
  transitions = dbGetQuery(
    conn, query, 
    params = c(
      modified_sequence,
      glycan_name,
      glycan_site,
      precursor_charge
    )
  )
  colnames(transitions) = tolower(colnames(transitions))
  
  dbDisconnect(conn)
  transitions
}


read.transition.scores = function(path, 
                                  modified_sequence,
                                  glycan_site,
                                  glycan_name,
                                  precursor_charge) {
  conn = dbConnect(RSQLite::SQLite(), path)
  
  query = "
  SELECT GLYCAN.GLYCAN_NAME AS GLYCAN,
  PRECURSOR_MZ,
  PRECURSOR.CHARGE AS PRECURSOR_CHARGE,
  LIBRARY_RT,
  PRODUCT_MZ,
  TRANSITION.CHARGE AS PRODUCT_CHARGE,
  TRANSITION.TYPE AS FRAGMENT_TYPE,
  ANNOTATION,
  GLYCOFORM.GLYCAN_NAME AS GLYCOFORM,
  FEATURE_TRANSITION.*
  FROM PRECURSOR
  INNER JOIN TRANSITION_PRECURSOR_MAPPING ON TRANSITION_PRECURSOR_MAPPING.PRECURSOR_ID = PRECURSOR.ID
  INNER JOIN TRANSITION ON TRANSITION.ID = TRANSITION_PRECURSOR_MAPPING.TRANSITION_ID
  
  INNER JOIN PRECURSOR_GLYCOPEPTIDE_MAPPING ON PRECURSOR_GLYCOPEPTIDE_MAPPING.PRECURSOR_ID = PRECURSOR.ID
  INNER JOIN GLYCOPEPTIDE ON GLYCOPEPTIDE.ID = PRECURSOR_GLYCOPEPTIDE_MAPPING.GLYCOPEPTIDE_ID
  INNER JOIN GLYCOPEPTIDE_PEPTIDE_MAPPING ON GLYCOPEPTIDE_PEPTIDE_MAPPING.GLYCOPEPTIDE_ID = GLYCOPEPTIDE.ID
  INNER JOIN PEPTIDE ON GLYCOPEPTIDE_PEPTIDE_MAPPING.PEPTIDE_ID = PEPTIDE.ID
  INNER JOIN GLYCOPEPTIDE_GLYCAN_MAPPING ON GLYCOPEPTIDE_GLYCAN_MAPPING.GLYCOPEPTIDE_ID = GLYCOPEPTIDE.ID
  INNER JOIN GLYCAN ON GLYCAN.ID = GLYCOPEPTIDE_GLYCAN_MAPPING.GLYCAN_ID
  
  INNER JOIN (
  SELECT TRANSITION_ID, 
  GLYCAN.*
  FROM TRANSITION_GLYCOPEPTIDE_MAPPING 
  INNER JOIN GLYCOPEPTIDE AS GLYCOPEPTIDE ON GLYCOPEPTIDE.ID = TRANSITION_GLYCOPEPTIDE_MAPPING.GLYCOPEPTIDE_ID
  INNER JOIN GLYCOPEPTIDE_GLYCAN_MAPPING ON GLYCOPEPTIDE_GLYCAN_MAPPING.GLYCOPEPTIDE_ID = GLYCOPEPTIDE.ID
  INNER JOIN GLYCAN ON GLYCAN.ID = GLYCOPEPTIDE_GLYCAN_MAPPING.GLYCAN_ID
  ) AS GLYCOFORM ON GLYCOFORM.TRANSITION_ID = TRANSITION.ID
  
  INNER JOIN (
  SELECT FEATURE.ID AS FEATURE_ID,
  FEATURE.RUN_ID AS RUN_ID,
  FEATURE.PRECURSOR_ID AS PRECURSOR_ID,
  FEATURE_TRANSITION.TRANSITION_ID AS TRANSITION_ID,
  SCORE_TRANSITION.PEP AS TRANSITION_PEP
  FROM FEATURE
  INNER JOIN SCORE_MS2 ON SCORE_MS2.FEATURE_ID = FEATURE.ID
  INNER JOIN FEATURE_TRANSITION ON FEATURE_TRANSITION.FEATURE_ID = FEATURE.ID
  INNER JOIN SCORE_TRANSITION ON SCORE_TRANSITION.FEATURE_ID = FEATURE.ID 
  AND SCORE_TRANSITION.TRANSITION_ID = FEATURE_TRANSITION.TRANSITION_ID
  WHERE SCORE_MS2.RANK = 1
  ) AS FEATURE_TRANSITION ON FEATURE_TRANSITION.TRANSITION_ID = TRANSITION.ID
  AND FEATURE_TRANSITION.PRECURSOR_ID = PRECURSOR.ID
  
  WHERE TRANSITION.IDENTIFYING = 1
  AND TRANSITION.DECOY = 0
  AND PEPTIDE.MODIFIED_SEQUENCE = ?
  AND GLYCAN.GLYCAN_NAME = ?
  AND GLYCOPEPTIDE.GLYCAN_SITE = ?
  AND PRECURSOR.CHARGE = ?
  "
  
  transitions = dbGetQuery(
    conn, query, 
    params = c(
      modified_sequence,
      glycan_name,
      glycan_site,
      precursor_charge
    )
  )
  colnames(transitions) = tolower(colnames(transitions))
  
  dbDisconnect(conn)
  transitions
}


read.precursors = function(path) {
  conn = dbConnect(RSQLite::SQLite(), path)
  
  query = "
SELECT PRECURSOR.ID AS transition_group_id,
       PRECURSOR.DECOY AS decoy,
       GLYCOPEPTIDE.DECOY_PEPTIDE AS decoy_peptide,
       GLYCOPEPTIDE.DECOY_GLYCAN AS decoy_glycan,
       PEPTIDE.UNMODIFIED_SEQUENCE AS Sequence,
       PEPTIDE.MODIFIED_SEQUENCE AS FullPeptideName,
       GLYCAN.GLYCAN_STRUCT AS GlycanStruct,
       GLYCAN.GLYCAN_COMPOSITION AS GlycanComposition,
       GLYCOPEPTIDE.GLYCAN_SITE AS GlycanSite,       
       PRECURSOR.CHARGE AS Charge,
       ProteinName,
       ProteinGlycoSite
FROM PRECURSOR
INNER JOIN PRECURSOR_GLYCOPEPTIDE_MAPPING ON PRECURSOR.ID = PRECURSOR_GLYCOPEPTIDE_MAPPING.PRECURSOR_ID
INNER JOIN GLYCOPEPTIDE ON PRECURSOR_GLYCOPEPTIDE_MAPPING.GLYCOPEPTIDE_ID = GLYCOPEPTIDE.ID
INNER JOIN GLYCOPEPTIDE_PEPTIDE_MAPPING ON GLYCOPEPTIDE.ID = GLYCOPEPTIDE_PEPTIDE_MAPPING.GLYCOPEPTIDE_ID
INNER JOIN PEPTIDE ON GLYCOPEPTIDE_PEPTIDE_MAPPING.PEPTIDE_ID = PEPTIDE.ID
INNER JOIN GLYCOPEPTIDE_GLYCAN_MAPPING ON GLYCOPEPTIDE.ID = GLYCOPEPTIDE_GLYCAN_MAPPING.GLYCOPEPTIDE_ID
INNER JOIN GLYCAN ON GLYCOPEPTIDE_GLYCAN_MAPPING.GLYCAN_ID = GLYCAN.ID

INNER JOIN (
  SELECT GLYCOPEPTIDE_ID,
         GROUP_CONCAT(PROTEIN.PROTEIN_ACCESSION,';') AS ProteinName,
         GROUP_CONCAT(GLYCOSITE.PROTEIN_GLYCOSITE,';') AS ProteinGlycoSite
  FROM GLYCOPEPTIDE_GLYCOSITE_MAPPING
  INNER JOIN GLYCOSITE ON GLYCOPEPTIDE_GLYCOSITE_MAPPING.GLYCOSITE_ID = GLYCOSITE.ID
  INNER JOIN GLYCOSITE_PROTEIN_MAPPING ON GLYCOSITE.ID = GLYCOSITE_PROTEIN_MAPPING.GLYCOSITE_ID
  INNER JOIN PROTEIN ON GLYCOSITE_PROTEIN_MAPPING.PROTEIN_ID = PROTEIN.ID
  GROUP BY GLYCOPEPTIDE_ID
) AS PROTEIN_GLYCOSITE ON PROTEIN_GLYCOSITE.GLYCOPEPTIDE_ID = GLYCOPEPTIDE.ID
"
  
  precursors = dbGetQuery(conn, query)
  
  dbDisconnect(conn)
  precursors
}
